### ISSUE TITLE
question of training dataset

### ISSUE THREAD

**Issue by linohzz** [HighwayWu/FOCAL#14]
Have you used all the images in CAT-net for training?

**Comment by HighwayWu** [comment]
We are actually using a subset of the CAT-Net training dataset, because some datasets (such as FantasticReality) are no longer available for open download. Please refer to the following table (i.e., Table 5 in arXiv paper) for specific data used for training FOCAL.
![微信截图_20240402165832](https://github.com/HighwayWu/FOCAL/assets/29557288/6e32c86e-9ae2-4019-a211-af1f6ee94a2e)
