### ISSUE TITLE
Running on AMD GPU? Is Nvidia CUDA required? Alternatives supported?

### ISSUE THREAD

**Issue by doteric** [HighwayWu/FOCAL#15]
Hello,

When running the `testing phase` to create a prediction from an input I am receiving `AssertionError: Torch not compiled with CUDA enabled`. I assume that means that NVIDIA CUDA is required, correct? I am running this on a macbook with AMD GPU  and I'm curious are there any available implemented alternatives or only Nvidia GPUs are supported?

Thank you!

**Comment by HighwayWu** [comment]
Sorry for the inconvenience. This project has only been tested on Linux systems and Nvidia GPUs.

**Comment by doteric** [comment]
Hey @HighwayWu   
Big thanks for the answer. I managed to get it running on a Linux server with Nvidia GPU, it works fine, but I'm often receiving false alarms, especially in scaled down images.  

Mentioned about this here: https://github.com/HighwayWu/FOCAL/issues/10#issuecomment-2109806135 

Also the following warnings occur:
```
/usr/local/lib64/python3.9/site-packages/torch/nn/modules/conv.py:456: UserWarning: Attempt to open cnn_infer failed: handle=0 error: libcudnn_cnn_infer.so.8: cannot open shared object file: No such file or directory (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:81.)
  return F.conv2d(input, weight, bias, self.stride,
/usr/local/lib/python3.9/site-packages/torch_kmeans/clustering/kmeans.py:530: UserWarning: standard k-means should use a non-inverted distance measure.
  warn("standard k-means should use a non-inverted distance measure.")
```
But the tool works fine even with those showing up.

**Comment by HighwayWu** [comment]
Hi, Doteric. Thank you for your questions.
1. False alarms (especially for real images) are a key issue we work to mitigate. It is recommended not to introduce additional scaling noise through down-scaling. Generally speaking, up-scaling could increase the detection performance to a certain extent.
2. These warnings are raised by the kmeans library. Because it does not affect the actual clustering, we have not tried to fix it. Some alternative measures, such as Euclidean distance, may be helpful.
3. Please refer to the explanation of [F1](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html) and [IoU](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.jaccard_score.html). And, yes, the results are the average of all test images.

**Comment by doteric** [comment]
Thank you for the response and explaining everything! Really appreciate it.  
Issue can be closed if you would like to. 👍
