### ISSUE TITLE
MISD dataset

### ISSUE THREAD

**Issue by xupinggl** [HighwayWu/FOCAL#7]
Hello, I have two questions about the dataset MISD: (1) In the data I downloaded from the official website at https://doi.org/10.5281/zenodo.5525829, one image corresponds to 2 masks, do I need to fuse the 2 masks into one mask before testing? (2) The MISD published here has 303 forged images, I see you only used 227, is it convenient to provide the txt of this dataset you used, or can you provide this dataset for both? Thank you very much.

**Comment by HighwayWu** [comment]
Thanks for your interest. Due to some errors (mismatch, etc.), I screened and verified the 303 pictures and only retained these 227 pictures. The MISD dataset used in the paper can be downloaded from this [link](https://drive.google.com/file/d/17acVu8Tal7pYu0cEeRQ8EBu6AIK188MG/view?usp=sharing) for your research / comparison.

**Comment by xupinggl** [comment]
您好，您的邮件我已收到，我会尽快回复的，谢谢！

**Comment by xupinggl** [comment]
> Thanks for your interest. Due to some errors (mismatch, etc.), I screened and verified the 303 pictures and only retained these 227 pictures. The MISD dataset used in the paper can be downloaded from this [link](https://drive.google.com/file/d/17acVu8Tal7pYu0cEeRQ8EBu6AIK188MG/view?usp=sharing) for your research / comparison.

Thank you very much.
